package org.smartsnip.core;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

import org.smartsnip.core.Code.UnsupportedLanguageException;

/**
 * A snippet of the system. TODO: Write me
 * 
 * The hash code if the snippet is the internal integer hash.
 * 
 */
public class Snippet {
	/** All stored snippets of the system */
	private final static HashMap<Integer, Snippet> allSnippets = new HashMap<Integer, Snippet>();

	/** Internal hash counter used to get the next hash */
	private static int hashCounter = 0;

	/** Owner (creator) of the snippet */
	public final User owner;
	/** Snippet name */
	private String name;
	/** Unique hash code of the snippet */
	public final int hash;
	/** Snippet description */
	private String description;
	/** Snippet associated category */
	private Category category;
	/** Tags of the snippet */
	private final List<Tag> tags = new ArrayList<Tag>();
	/** Comments of the snippet */
	private final List<Comment> comments = new ArrayList<Comment>();
	/** Concrete snippet code */
	private Code code;
	/** Licence of the snippet. By default GPLv3 */
	private String license = "GPLv3";
	/** View counter */
	private int viewcount = 0;

	@Override
	public int hashCode() {
		return hash;
	}

	/**
	 * Constructor with all fields that MUST be initialised. If one of the field
	 * is null a {@link NullPointerException} will be thrown. If one of the
	 * field is empty, a {@link IllegalArgumentException} will be thrown
	 * 
	 * @param owner
	 *            the owner of the snippet
	 * @param name
	 *            snippet's name
	 * @param description
	 *            a short description
	 * @param code
	 *            the code of the snippet
	 * @param hash
	 *            hash code of the snippet
	 * @throws IllegalArgumentException
	 *             Thrown if one of the arguments is illegal
	 * @throws IllegalStateException
	 *             Thrown if the hash code is already in the system
	 */
	private Snippet(User owner, String name, String description, Code code, int hash) {
		if (owner == null || name == null || description == null || code == null) throw new NullPointerException();
		if (name.length() == 0) throw new IllegalArgumentException("Snippet name cannot be empty");
		if (description.length() == 0) throw new IllegalArgumentException("Snippet description cannot be empty");
		if (exists(hash)) throw new IllegalStateException("Given hash code already exists");

		this.owner = owner;
		this.name = name;
		this.description = description;
		this.code = code;
		this.hash = hash;
	}

	/**
	 * Creates a new snippet with the given parameters.
	 * 
	 * The hash code is automatically generated by getting the next available
	 * hash code.
	 * 
	 * 
	 * @param owner
	 *            of the snippet. Must not be null
	 * @param name
	 *            of the snippet. Must not be null or empty
	 * @param description
	 *            of the snippet. Must not be null or empty
	 * @param code
	 *            of the snippet. Must not be null or empty
	 * @param langauge
	 *            Coding language of the snippet. Must not be null or empty and
	 *            must be accepted by the system. If the language is not
	 *            supported, the thrown {@link UnsupportedLanguageException} is
	 *            packed into an {@link IllegalArgumentException}
	 * @return the generated snippet
	 * @throws NullPointerException
	 *             Thrown if one of the arguments if null
	 * @throws IllegalArgumentException
	 *             Thrown if one of the arguments if empty or not in the right
	 *             format or if the given language is not supported. If this
	 *             exception is thrown a description is set. If the language was
	 *             not supported, the cause is set to the
	 *             {@link UnsupportedLanguageException}.
	 */
	synchronized static Snippet createSnippet(User owner, String name, String description, String code, String language) {
		if (code == null || language == null) throw new NullPointerException();

		// Create code object
		Code codeObj = null;
		try {
			codeObj = Code.createCode(code, language);
		} catch (UnsupportedLanguageException e) {
			throw new IllegalArgumentException(e.getMessage(), e);
		}
		return createSnippet(owner, name, description, codeObj);
	}

	/**
	 * Creates a new snippet with the given parameters.
	 * 
	 * The hash code is automatically generated by getting the next available
	 * hash code.
	 * 
	 * 
	 * @param owner
	 *            of the snippet. Must not be null
	 * @param name
	 *            of the snippet. Must not be null or empty
	 * @param description
	 *            of the snippet. Must not be null or empty
	 * @param code
	 *            of the snippet. Must not be a null objet.
	 * @return the generated snippet
	 * @throws NullPointerException
	 *             Thrown if one of the arguments if null
	 * @throws IllegalArgumentException
	 *             Thrown if one of the arguments if empty or not in the right
	 *             format. If this exception is thrown a description is set
	 */
	synchronized static Snippet createSnippet(User owner, String name, String description, Code code) {
		return createSnippet(owner, name, description, code, getNextHashCode());
	}

	synchronized static Snippet createSnippet(User owner, String name, String description, Code code, int hash) {
		Snippet snippet = new Snippet(owner, name, description, code, hash);
		addToDB(snippet);
		return snippet;
	}

	/**
	 * @return the next available hash code
	 */
	private synchronized static int getNextHashCode() {
		while (exists(++hashCounter)) {
			;
		}
		return hashCounter;
	}

	/**
	 * Checks if the given hash code exists
	 * 
	 * @param hash
	 *            to be checks
	 * @return true if already registered hash, otherwise false
	 */
	synchronized static boolean exists(int hash) {
		return allSnippets.containsKey(hash);
	}

	/**
	 * Searches for a snipped by his hash code and returns it if found. If no
	 * snippet is found, null is returned
	 * 
	 * @param hash
	 *            hash code of the snippet
	 * @return the found snippet or null if not existsing
	 */
	synchronized static Snippet getSnippet(int hash) {
		return allSnippets.get(hash);
	}

	/**
	 * @return the name
	 */
	String getName() {
		return name;
	}

	/**
	 * Sets the name of the snippet. If the name is null or empty, nothing will
	 * be done.
	 * 
	 * @param name
	 *            the name to set
	 */
	void setName(String name) {
		if (name == null || name.length() == 0) return;
		if (this.name.equals(name)) return;

		this.name = name;
		refreshDB();
	}

	/**
	 * @return the description
	 */
	String getDescription() {
		return description;
	}

	/**
	 * Sets the description of the snippet. If the description is empty or null,
	 * nothing is done.
	 * 
	 * @param description
	 *            the description to set
	 */
	void setDescription(String description) {
		if (description == null || description.length() == 0) return;
		if (this.description.equals(description)) return;

		this.description = description;
		refreshDB();
	}

	/**
	 * @return the code of the snippet
	 */
	Code getCode() {
		return code;
	}

	/**
	 * Sets the code of the snippet. If null, nothing is done.
	 * 
	 * @param code
	 *            the code to set
	 */
	void setCode(Code code) {
		if (code == null) return;
		if (this.code.equals(code)) return;

		this.code = code;
		refreshDB();
	}

	@Override
	public String toString() {
		return "Snippet: " + name;
	}

	/**
	 * @return the category of the snippet
	 */
	public Category getCategory() {
		return category;
	}

	/**
	 * Set the snippet category. If null nothing happens.
	 * 
	 * This call removes the snippet from the old category and adds the snippet
	 * to the new category.
	 * 
	 * @param category
	 *            the category to set
	 */
	void setCategory(Category category) {
		if (category == null) return;
		if (this.category == category) return;

		if (this.category != null) {
			this.category.removeSnippet(this);
		}
		this.category = category;
		category.addSnippet(this);
		refreshDB();
	}

	/**
	 * @return the license of the snippet
	 */
	public String getLicense() {
		return license;
	}

	/**
	 * Sets the new license of the snippet. If the license is null or empty,
	 * nothing will be done
	 * 
	 * @param license
	 *            the license to set
	 */
	void setLicense(String license) {
		if (license == null || license.length() == 0) return;
		if (this.license.equals(license)) return;
		this.license = license;
		refreshDB();
	}

	/**
	 * @return the tags of the snippet
	 */
	List<Tag> getTags() {
		return tags;
	}

	/**
	 * Adds a tag to the snippet. If the given tag is null, nothing will be
	 * done. If the snippet has already been tagged with the tag, nothing is
	 * done.
	 * 
	 * @param tag
	 *            to be added to the snippet
	 */
	void addTag(Tag tag) {
		if (tag == null) return;
		synchronized (tags) {
			if (tags.contains(tag)) return;
			tags.add(tag);
		}
		refreshDB();
	}

	/**
	 * Removes a tag from the snippet. If the given tag is null, nothing will be
	 * done. If the snippet has not been tagged with the tag, nothing is done.
	 * 
	 * @param tag
	 *            to be removed from the snippet
	 */
	void removeTag(Tag tag) {
		if (tag == null) return;
		synchronized (tags) {
			if (!tags.contains(tag)) return;
			tags.remove(tag);
		}
		refreshDB();
	}

	/**
	 * @return the comments of the snippet
	 */
	List<Comment> getComments() {
		return comments;
	}

	/**
	 * @return the counts of view
	 */
	int getViewcount() {
		return viewcount;
	}

	synchronized void increaseViewCounter() {
		viewcount++;
		refreshDB();
	}

	/**
	 * Adds a comment to the snippet. If the comment is null, nothing will be
	 * done. If comment has already been added, nothing is done
	 * 
	 * @param comment
	 *            to be added
	 */
	void addComment(Comment comment) {
		if (comment == null) return;
		synchronized (comments) {
			if (comments.contains(comment)) return;
			comments.add(comment);
		}
		refreshDB();
	}

	/**
	 * Removes a comment from the snippet. If the comment is null, the nothing
	 * is done. If the given comment is not in the comments list of the snippet
	 * also the method returns without effect.
	 * 
	 * @param comment
	 *            to be removed
	 */
	void removeComment(Comment comment) {
		if (comment == null) return;
		synchronized (comments) {
			if (!comments.contains(comment)) return;
			comments.remove(comment);
		}
		refreshDB();
	}

	/**
	 * Checks if the snippet has a given tag
	 * 
	 * @param tag
	 *            to be checked
	 * @return true if the snippet has been tagged with the given tag, otherwise
	 *         false
	 */
	boolean hasTag(Tag tag) {
		if (tag == null) return false;
		return tags.contains(tag);
	}

	/**
	 * @return the owner of the session
	 */
	public User getOwner() {
		return owner;
	}

	/**
	 * 
	 * @return the total number of snippets in the system
	 */
	static int totalCount() {
		return allSnippets.size();
	}

	/**
	 * Invokes the refreshing process for the database
	 */
	protected void refreshDB() {
		// TODO: Implement me!
	}

	/**
	 * Adds the given snippet to the database. If null, nothing happens
	 * 
	 * @param snippet
	 *            to be added.
	 */
	static protected void addToDB(Snippet snippet) {
		if (snippet == null) return;

		allSnippets.put(snippet.hash, snippet);
		// TODO: Implement me!
	}

	/**
	 * Deletes the snippet
	 */
	void delete() {
		// TODO Auto-generated method stub

	}
}
